// api/generate-docx.js
// Serverless function — converts plain text content into a properly formatted .docx file
// Uses the `docx` npm package to produce a real Word document (not an HTML blob)

import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle, Table, TableRow, TableCell,
  WidthType, ShadingType, convertInchesToTwip, Header, Footer,
  PageNumber, NumberFormat
} from "docx";

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { content, filename = "ProLaunch_Document", type = "default" } = req.body || {};
  if (!content) return res.status(400).json({ error: "Content is required." });

  try {
    const doc = buildDocument(content, type);
    const buffer = await Packer.toBuffer(doc);

    const safeFilename = filename.replace(/[^a-zA-Z0-9_\-]/g, "_");
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    res.setHeader("Content-Disposition", `attachment; filename="${safeFilename}.docx"`);
    res.setHeader("Content-Length", buffer.length);
    return res.status(200).send(buffer);

  } catch (err) {
    console.error("generate-docx error:", err);
    return res.status(500).json({ error: "Failed to generate document: " + err.message });
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// COLOURS & STYLES
// ─────────────────────────────────────────────────────────────────────────────
const FOREST  = "124745";
const GREEN   = "7BB640";
const GRAY    = "6B7280";
const WHITE   = "FFFFFF";
const CREAM   = "F7F9F4";

function brandHeading(text, level = HeadingLevel.HEADING_1) {
  const sizes = { [HeadingLevel.HEADING_1]: 32, [HeadingLevel.HEADING_2]: 26, [HeadingLevel.HEADING_3]: 22 };
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({
      text,
      bold: true,
      color: FOREST,
      size: sizes[level] || 24,
      font: "Calibri",
    })],
  });
}

function bodyParagraph(text, { bold = false, italic = false, color = "374151", spacing = { before: 40, after: 40 } } = {}) {
  return new Paragraph({
    spacing,
    children: [new TextRun({ text, bold, italic, color, size: 22, font: "Calibri" })],
  });
}

function divider() {
  return new Paragraph({
    spacing: { before: 120, after: 120 },
    border: { bottom: { color: GREEN, style: BorderStyle.SINGLE, size: 6 } },
    children: [],
  });
}

function greenLabel(text) {
  return new Paragraph({
    spacing: { before: 200, after: 60 },
    children: [new TextRun({ text: text.toUpperCase(), bold: true, color: GREEN, size: 18, font: "Calibri" })],
  });
}

function watermarkFooter() {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: "Generated by ProLaunch Careers  •  prolaunch-cv-optimizer.vercel.app", size: 16, color: "9CA3AF", font: "Calibri" }),
        ],
      }),
    ],
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// DOCUMENT BUILDER — dispatches by type
// ─────────────────────────────────────────────────────────────────────────────
function buildDocument(content, type) {
  switch (type) {
    case "cv":        return buildCVDoc(content);
    case "analysis":  return buildAnalysisDoc(content);
    case "letter":    return buildLetterDoc(content);
    case "interview": return buildInterviewDoc(content);
    case "insights":  return buildInsightsDoc(content);
    default:          return buildGenericDoc(content);
  }
}

// ─── Generic fallback ────────────────────────────────────────────────────────
function buildGenericDoc(content) {
  const lines = String(content).split("\n");
  const children = [
    coverBlock("ProLaunch Careers", "Career Document"),
    divider(),
    ...lines.map(line => {
      if (!line.trim()) return new Paragraph({ spacing: { before: 80, after: 80 }, children: [] });
      if (line.startsWith("# "))  return brandHeading(line.slice(2), HeadingLevel.HEADING_1);
      if (line.startsWith("## ")) return brandHeading(line.slice(3), HeadingLevel.HEADING_2);
      if (line.startsWith("### "))return brandHeading(line.slice(4), HeadingLevel.HEADING_3);
      if (line.startsWith("- ") || line.startsWith("• ")) {
        return new Paragraph({ bullet: { level: 0 }, spacing: { before: 40, after: 40 }, children: [new TextRun({ text: line.replace(/^[-•]\s+/, ""), size: 22, font: "Calibri", color: "374151" })] });
      }
      return bodyParagraph(line);
    }),
  ];
  return new Document({
    sections: [{ properties: {}, footers: { default: watermarkFooter() }, children }],
  });
}

// ─── CV / Resume ─────────────────────────────────────────────────────────────
function buildCVDoc(content) {
  const text  = String(content);
  const lines = text.split("\n");

  const CV_SECTIONS = ["professional summary", "core competencies", "professional experience",
    "work experience", "experience", "education", "certifications", "skills", "achievements"];

  const children = [];
  for (const line of lines) {
    if (!line.trim()) { children.push(new Paragraph({ spacing: { before: 60, after: 60 }, children: [] })); continue; }
    const lower = line.trim().toLowerCase();
    if (CV_SECTIONS.some(s => lower.startsWith(s))) {
      children.push(greenLabel(line.trim()));
      children.push(divider());
    } else if (line.trim().length < 60 && !line.includes("|") && !line.includes("•") && !line.includes("-") && lines.indexOf(line) < 5) {
      // Likely the person's name at the top
      children.push(new Paragraph({ spacing: { before: 80, after: 40 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: line.trim(), bold: true, size: 36, color: FOREST, font: "Calibri" })] }));
    } else if (line.startsWith("•") || line.startsWith("-") || line.trim().startsWith("·")) {
      children.push(new Paragraph({ bullet: { level: 0 }, spacing: { before: 30, after: 30 }, children: [new TextRun({ text: line.replace(/^[•\-·]\s*/, "").trim(), size: 21, font: "Calibri", color: "374151" })] }));
    } else {
      children.push(bodyParagraph(line.trim()));
    }
  }

  return new Document({
    sections: [{ properties: {}, footers: { default: watermarkFooter() }, children }],
  });
}

// ─── CV Analysis Report ───────────────────────────────────────────────────────
function buildAnalysisDoc(content) {
  // content is either a plain string or JSON string of { score, role, strengths, gaps, missing_keywords, quick_wins, recommendation }
  let parsed = null;
  try { parsed = typeof content === "object" ? content : JSON.parse(content); } catch (_) {}

  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const children = [
    coverBlock("CV Analysis Report", `Generated on ${now}`),
    divider(),
  ];

  if (parsed && typeof parsed === "object") {
    if (parsed.role) {
      children.push(greenLabel("Target Role"));
      children.push(bodyParagraph(parsed.role, { bold: true }));
    }
    if (parsed.score !== undefined) {
      children.push(greenLabel("ATS Score"));
      children.push(bodyParagraph(`${parsed.score} / 100`, { bold: true, color: GREEN }));
    }
    const sections = [
      ["Strengths",         parsed.strengths],
      ["Gaps & Weaknesses", parsed.gaps],
      ["Missing Keywords",  parsed.missing_keywords],
      ["Quick Wins",        parsed.quick_wins],
      ["Recommendation",    parsed.recommendation],
    ];
    for (const [label, text] of sections) {
      if (!text) continue;
      children.push(greenLabel(label));
      children.push(...textToParas(String(text)));
    }
  } else {
    children.push(...textToParas(String(content)));
  }

  return new Document({
    sections: [{ properties: {}, footers: { default: watermarkFooter() }, children }],
  });
}

// ─── Cover Letter ─────────────────────────────────────────────────────────────
function buildLetterDoc(content) {
  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const lines = String(content).split("\n");
  const children = [
    new Paragraph({ spacing: { before: 0, after: 200 }, alignment: AlignmentType.RIGHT, children: [new TextRun({ text: now, size: 21, color: GRAY, font: "Calibri" })] }),
    ...lines.map(line => {
      if (!line.trim()) return new Paragraph({ spacing: { before: 80, after: 80 }, children: [] });
      return bodyParagraph(line, { spacing: { before: 60, after: 60 } });
    }),
    new Paragraph({ spacing: { before: 300, after: 80 }, children: [new TextRun({ text: "Yours sincerely,", size: 22, font: "Calibri", color: "374151" })] }),
  ];
  return new Document({
    sections: [{ properties: {}, footers: { default: watermarkFooter() }, children }],
  });
}

// ─── Interview Prep ───────────────────────────────────────────────────────────
function buildInterviewDoc(content) {
  const lines = String(content).split("\n");
  const children = [
    coverBlock("Interview Preparation Guide", "ProLaunch Careers"),
    divider(),
  ];
  let qNum = 0;
  for (const line of lines) {
    if (!line.trim()) { children.push(new Paragraph({ spacing: { before: 80, after: 80 }, children: [] })); continue; }
    if (/^(Q\d+|Question\s*\d+|^\d+[\.\)])/i.test(line.trim())) {
      qNum++;
      children.push(new Paragraph({
        spacing: { before: 200, after: 60 },
        children: [new TextRun({ text: line.trim(), bold: true, size: 23, color: FOREST, font: "Calibri" })],
      }));
    } else if (/^(A:|Answer:|Model Answer)/i.test(line.trim())) {
      children.push(new Paragraph({
        spacing: { before: 60, after: 40 },
        children: [new TextRun({ text: line.trim(), bold: true, size: 21, color: GREEN, font: "Calibri" })],
      }));
    } else {
      children.push(bodyParagraph(line.trim()));
    }
  }
  return new Document({
    sections: [{ properties: {}, footers: { default: watermarkFooter() }, children }],
  });
}

// ─── Career Insights ─────────────────────────────────────────────────────────
function buildInsightsDoc(content) {
  const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const children = [
    coverBlock("Career Insights Report", `Generated on ${now}`),
    divider(),
    ...textToParas(String(content)),
  ];
  return new Document({
    sections: [{ properties: {}, footers: { default: watermarkFooter() }, children }],
  });
}

// ─── Helpers ─────────────────────────────────────────────────────────────────
function coverBlock(title, subtitle) {
  return new Paragraph({
    spacing: { before: 0, after: 160 },
    children: [
      new TextRun({ text: title, bold: true, size: 40, color: FOREST, font: "Calibri", break: 0 }),
      new TextRun({ text: `\n${subtitle}`, size: 22, color: GRAY, font: "Calibri", break: 1 }),
    ],
  });
}

function textToParas(text) {
  return text.split("\n").map(line => {
    if (!line.trim()) return new Paragraph({ spacing: { before: 60, after: 60 }, children: [] });
    if (line.startsWith("•") || line.startsWith("-") || line.trim().startsWith("·")) {
      return new Paragraph({ bullet: { level: 0 }, spacing: { before: 30, after: 30 }, children: [new TextRun({ text: line.replace(/^[•\-·]\s*/, "").trim(), size: 21, font: "Calibri", color: "374151" })] });
    }
    return bodyParagraph(line.trim());
  });
}